# Generated by Django 2.2.7 on 2019-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('discription', models.CharField(max_length=500, null=True)),
                ('video_id', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
