# Generated by Django 2.2.7 on 2019-12-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_details',
            name='channel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
