# Generated by Django 2.2.7 on 2020-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_home_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_videos',
            name='fake_percent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video_details',
            name='fake_percent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
